services:
  vite: 
    image: node:24
    command: sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run dev"
    volumes: 
      - ".:/usr/src/app" 
    working_dir: /usr/src/app 
    ports: 
      - "5173:5173"
      - "4173:4173"